### ISSUE TITLE
cp: cannot create regular file '/mopidy/mopidy.conf': Permission denied

### ISSUE THREAD

**Issue by wu-lee** [IVData/dockerfiles#18]
I'm just giving this a go, and mopidy runs but doesn't seem to be working quite right. For example, clients can't connect. Looking at the logs, I see this:

    cp: cannot create regular file '/mopidy/mopidy.conf': Permission denied

And reading the Dockerfile, I think what's happening is the init script `/usr/local/bin/mopidy.sh` is run as the `mopidy` user, which doesn't have write access to `/mopidy/` to create `mopidy.conf`

**Comment by gitisz** [comment]
I see the same behavior is addition to this:
> WARNING  2021-02-14 14:14:21,042 [1:MainThread] mopidy.__main__
> Unable to initialize file:///mopidy/mopidy.conf with default config: [Errno 13] Permission denied: '/mopidy/mopidy.conf'

**Comment by gitisz** [comment]
@wu-lee Looks like this is because the host volume where the mopidy.conf file is copied to doesn't share the same UID as the mopidy user the container is set to run as.

https://github.com/IVData/dockerfiles/blob/master/mopidy/Dockerfile#L59

I ran `chown 1000:1000 /data/compose/<#>/mopidydata` on the folders that were created by docker compose on the host.  1000 is the UID I believe of the mopidy user running in the container.  You can run `cat /etc/passwd` to find out for certain.

**Comment by hamishfagg** [comment]
You could likely just give 777 permissions to this folder too.

**Comment by spiro-c** [comment]
If you pre create mopidydata folder whit your user before starting the docker-compose or docker container you wont have problem if docker need to create that folder what you map inside container docker will create that folder like root

**Comment by wu-lee** [comment]
I managed to get this container working temporarily by launching a shell in the container and running:

    chmod -R mopidy:mopidy /mopidy

What I suspect would fix it permanently is executing this in the Dockerfile.

**Comment by hamishfagg** [comment]
Added this fix to the dockerfile
