### ISSUE TITLE
Update Snapcast Client & Server to 0.13

### ISSUE THREAD

**Issue by jokerigno** [IVData/dockerfiles#3]
Hi,

It's me, again!

Please notice that there's a new update to 0.13.

Can you please update it?

Thank you

**Comment by hamishfagg** [comment]
Hi.
I've updated all of these now and pushed to dockerhub. Let me know if you have any issues :)

Thanks

**Comment by jokerigno** [comment]
I downloade again the  files from docker. Cleaned the container and then restarted. 
But if I run snapserver -v i see 0.12!

**Comment by jokerigno** [comment]
Oh, another question. 

I used mopidy + snapcast for a while and noticed that when I add multiple device or when my network is doing "things" the buffer is not enough (some chuck are skipped and so on). Looking at snapcast github the developer suggested to play around with buffer (https://github.com/badaix/snapcast/issues/227). This value can be changed in the entrypoint (for example -b 2000 againt the default 1000). 
Do you think it should be possible to modify it? or to make as variable?

Finally. After the last update I notice that mopidy-iris is correctly downloaded but not started. Did you noticed it?

**Comment by hamishfagg** [comment]
> But if I run snapserver -v i see 0.12!

You're right. Sorry, I will have to fix it hopefully tonight

> Do you think it should be possible to modify it? or to make as variable?

Yes, this is a good idea. What I could do is add it as another env var like STREAM_NAME. Or, it may be easier to allow people to mount /etc/default/snapserver (will let people define multiple streams etc). Because the container starts snapserver with some options already, im not sure if the config file will overwrite these.

> mopidy-iris is correctly downloaded but not started

I haven't noticed. Can you send me the logs from your mopidy please?

I'm currently trying to set up all automated builds for this stuff for x64 and ARM, so something may have gone wrong. I will test tonight =) the latest build I haven't actually tested on my server so please be patient =) this will all hopefully mean updates in the future are easier.

**Comment by hamishfagg** [comment]
Just a friendly request from me:

When you have a question/problem that's not related to this issue, can you please create a new issue for it? I know that it will mean that I get flooded with issues somewhat, but I think it will help with people searching later on.

Don't worry about the questions you've already asked here. But just for future ones.  
Again, thanks for being patient and reporting bugs to me 


EDIT:
Just an update. The snapcast version issue seems to be a problem with the manifest that directs docker to download either the amd64 or armhf version. If you use ivdata/snapserver:amd64 you will have 0.13, but not if you use ivdata/snapserver:latest. I will get this fixed though

**Comment by hamishfagg** [comment]
### Snapserver showing v0.12

This is now fixed. Tested on my machine

### Snapserver buffer setting

This container has been changed so that you can now overwrite /etc/default/snapserver (mount it with docker). You can look in the repo to see the default settings (snapserver.conf). So you can set any settings you want =)

### Mopidy-iris not playing

The container was missing some gstreamer packages. I have tested this on my machine now and Iris is running and playing music.

Please test and let me know if you have any trouble.

**Comment by jokerigno** [comment]
OOOOOK!

Snapserver and client are now Update.

Snapserver configuration is now exposed. So I started playing around with it.

Mopidy Iris: unfortunately nothing changes. It is installed but it is still disabled at startup.  :(

**Comment by hamishfagg** [comment]
Can you se nd me the logs from startup please? Including the command you ran.

**Comment by jokerigno** [comment]
OK.

I recreated the container from scratch.

Here are the settings:

https://pastebin.com/TMvdWnxE

Here are the container logs since the first boot:

https://pastebin.com/ChuSSUS3

I noticed something that may be intresting (dunno if releated or not)

1. tornado packages is installed, updated and kept in different versions (5.0.2, 4.5.3, 4.2.1 etc).

2. Pip can be ugraded: 
You are using pip version 8.1.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by hamishfagg** [comment]
1. This is a bug in the Mopidy-Iris package. See here: https://github.com/jaedb/Iris/issues/275
You could _probably_ fix this by specifying a version of tornado in your PIP_PACKAGES (try adding `tornado==4.5.3`)

2. Thanks for pointing this out. I will add the pip upgrade command into the dockerfile at some point.

**Comment by jokerigno** [comment]
WOW!

Done!

I uninstalled tornado and then run pip install tornado==4.5.3. 

Finally I remove the UPDATE variable to avoid any updates.

And now IRIS is there!

**Comment by hamishfagg** [comment]
Cool. Glad everything got sorted out. 👍 
Feel free to open more issues if have more problems.
